line-length = 120
src = ["src"]
target-version = "py311"
fix = true
select = ["E4", "E7", "E9", "F", "B", "I"]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"


[lint]
select = ["E4", "E7", "E9", "F", "B", "I"]
ignore = ["B008"]

[isort]
combine-as-imports = true
